### ISSUE TITLE
Comparator is not used in median_index

### ISSUE THREAD

**Issue by Morwenn** [danlark1/miniselect#2]
I was trying to replace my use of `std::nth_element` with miniselect's implementation of Andrei Alexandrescu's adaptive quickselect, but I ran into an issue while doing so: it seems that one of the `median_index` overloads does not consistently use the given comparator to compare elements (lines marked with `HERE`):

```cpp
template <class Iter, class Compare,
          class DiffType = typename std::iterator_traits<Iter>::difference_type>
inline DiffType median_index(const Iter r, DiffType a, DiffType b, DiffType c,
                             Compare&& comp) {
  if (r[a] > r[c]) std::swap(a, c); // HERE
  if (r[b] > r[c]) return c; // HERE
  if (comp(r[b], r[a])) return a;
  return b;
}
````

I stumbled upon this issue while trying to sort with a custom predicate a collection of a type that doesn't have comparison operators, so I fortunately got into a compile-time error, but I believe that it can result into more subtle runtime errors too when the types to sort do implement comparison operators.

Anyway, thanks again for this library, I'm glad to see selection algorithms getting some love 😄

**Comment by danlark1** [comment]
Thanks, will fix shortly !

**Comment by danlark1** [comment]
0.4.0 fixed, thank you. Everybody should use this version, my bad I didn't notice and somehow testing did not catch the failure -- in one test I was comparing pointers and all sanitizers were good :(

**Comment by Morwenn** [comment]
No problem, I plan to use the algorithm to replace libc++'s `nth_element` in one of my rather well-tested projects - I only noticed recently that it was O(n²) -, so I will tell you if I find anything else. Thanks for the quick fix 🙂
